### PR TITLE
Update to version 3.36.

### LINKED ISSUE #7: Devhelp uses EOLed runtime
Flatpak started to give me:
Info: org.gnome.Sdk is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
Info: org.gnome.Sdk.Locale is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.

Trying to uninstall this org.gnome.Sdk runtime ends up with:
Error: Can't remove org.gnome.Sdk/x86_64/3.32, it is needed for: org.gnome.Devhelp/x86_64/stable
error: Failed to uninstall org.gnome.Sdk: Can't remove org.gnome.Sdk/x86_64/3.32, it is needed for: org.gnome.Devhelp/x86_64/stable

Please update to use org.gnome.Sdk 3.36

### PR DESCRIPTION
**Pull request by akurtakov**
Including org.gnome.Sdk 3.36 update.

Fixes #7

### CODE REVIEW

**Comment by akurtakov** [comment]
@mbooth101 is it infra failure or smth I did wrong?

**Comment by nedrichards** [comment]
infra failure i think.

**Comment by ghost** [comment]
Thanks, merged. I've tested the change locally and it works fine.

**Comment by akurtakov** [comment]
It's still not on flathub. When would that happen?

**Pull request closed without merging**
