### PR TITLE
Update to 3.30.0

### PR DESCRIPTION
**Pull request by alice-mkh**
Based on upstream manifest

### CODE REVIEW

**Comment by ghost** [comment]
What a coincidence, I created the wip/misc branch yesterday. But because of a bug in flatpak or flathub I'm unable to test locally my commit, so I will retry later.

**Comment by ghost** [comment]
(not yesterday but Wednesday, I mean).

**Comment by alice-mkh** [comment]
Any progress?

**Comment by ghost** [comment]
I've tried again, still the same problem, I've filed https://github.com/flathub/flathub/issues/692 .

**Comment by alice-mkh** [comment]
Any progress? https://github.com/flathub/flathub/issues/692 looks like a one-time problem.

**Comment by TingPing** [comment]
I merged (and tested) his branch since it doesn't make sense to block on a network issue.

**Pull request closed without merging**
