### PR TITLE
Update v3.28.0

### PR DESCRIPTION
**Pull request by LeandroStanger**
News in 3.28.0, 2018-03-10
--------------------------
* Improve default GSettings values.
* A few other small improvements.
* Translation updates.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for the pull request.

You should read all news from 3.26 to 3.28, including all the 3.27.x.

For 3.27.90 you can see that there is a new configure option: `--enable-flatpak-build`, you should add it to the Flatpak manifest.

@alexlarsson : I can become a co-maintainer of this repo if you want (I'm the upstream maintainer of Devhelp).

**Comment by nedrichards** [comment]
@swilmet I've sent you an invitation to the repo - we'd *much* prefer if apps were maintained by upstream. Thanks!

**Comment by ghost** [comment]
Invitation accepted, thanks.

**Comment by ghost** [comment]
I've updated Devhelp to 3.28.0, see: https://github.com/flathub/org.gnome.Devhelp/commit/b30c5b2b5277bf8597ee689daa56ffd1f90dea80

**Pull request closed without merging**
